def dna_to_rna(dna):
    return ''.join('U' if x == 'T' else x for x in dna)

print(dna_to_rna("TTTT"))
print(dna_to_rna("GCAT"))
print(dna_to_rna("GACCGCCGCC"))
print(dna_to_rna("GCCACTGTGGAGAAACTTATCTACTACTCGGCCCACGATTGACTGACGCATACTCGGACGTCGTCCGGACCTGGCATTCGCTAGAGACGTTGCCCTCGCTATCCCAGAGGCACAACGCCCCGCGTGGTTAGGCCTCTGAAATAGGTACTCCTAATGCTTGCTCACAAATACCGCAAACTACAACTGTAGTCCGAGAATTATTTGGCTACGTAAATCCGAAATCTTTAAGGAGTAGGGCTCTATCCAGAGTAATAGCAAATGCGTCATCCTCAGGAAAAACAA"))